name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://Tehreem56:${{ secrets.HF }}@huggingface.co/spaces/Tehreem56/MLops-demo-workspace
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://Tehreem56:${{ secrets.HF }}@huggingface.co/spaces/Tehreem56/MLops-demo-workspace main
